repos:
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: ''  # Use the latest version of pylint
    hooks:
    -   id: pylint
-   repo: https://github.com/pre-commit/mirrors-flake8
    rev: ''  # Use the latest version of flake8
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-black
    rev: ''  # Use the latest version of black
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: ''  # Use the latest version of isort
    hooks:
    -   id: isort
